version: '2.21'

services:
  redis:
    image: redis:latest
    command: redis-server
    restart: on-failure
    ports:
      - 6379:6379

  bot:
    build: .
    command:  sh -c "python3 main.py"
    restart: always
    volumes:
      - .:/usr/app/src

  webhook:
    build: .
    command:  sh -c "uvicorn webhook:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    environment:
      DB_NAME: love
      BOT_TOKEN: 5641936553:rjtsrtjsrtjsrtjsrtjsrtjsrtjsrtj-VGyf_uaM
    volumes:
      - .:/usr/app/src
    ports:
      - 8000:8000
